---
# roles/k3s_worker/tasks/main.yml
- name: Install K3s agent and join cluster
  become: true
  shell: |
    set -eu

    # 1. 설치 스크립트 다운로드
    curl -fL https://get.k3s.io -o /tmp/k3s_install.sh
    chmod +x /tmp/k3s_install.sh

    # 2. 마스터 노드 정보(Private IP) 및 동적 라벨(tags.Role) 주입하여 실행
    K3S_URL="https://{{ hostvars[groups['master'][0]]['private_ip_address'] }}:6443" \
    K3S_TOKEN="{{ hostvars[groups['master'][0]]['k3s_token'] }}" \
    INSTALL_K3S_EXEC="agent --node-label node-role={{ tags.Role }}" \
    /tmp/k3s_install.sh
  args:
    executable: /bin/bash
    creates: /usr/local/bin/k3s-agent