---
mysql_user: "exporter"
mysql_password: "exporter"
mysql_host: "192.168.200.133"
mysql_port: 3306
# [수정] namespace는 예약어이므로 충돌 방지를 위해 변수명 변경
my_ns: "monitoring"
release_name: "mysql-exporter"
# [추가] 랜덤 포트 대신 우리가 사용할 고정 포트 정의
target_node_port: 30104