# group_vars/monitoring_server.yml
---
target_user: "ubuntu"
monitoring_dir: "/home/{{ target_user }}/monitoring"

# 그라파나(Grafana)
grafana_admin_password: "admin" # 실제 사용할 비번
grafana_port: 3000

# 프로메테우스(Prometheus)
prometheus_retention_time: "2d"
prometheus_retention_size: "300MB"
prometheus_port: 9090

# 자동 다운로드할 대시보드 정보
dashboard_ids:
  - { id: 12708, revision: 1 } # NGINX exporter
  - { id: 1860, revision: 31 } # Node Exporter Full
  - { id: 15282, revision: 1 } # K3S cluster monitoring
  - { id: 7362, revision: 5 } # MySQL Overview
# Discord 또는 Slack에서 만든 Webhook URL
alert_webhook_url: "https://discord.com/api/webhooks/1468844118750007492/vKKoldUKN4q-olnZFcsg9_7pyxnxbb4snoAhw1VwZLZH-WmZfvo5FLCz9YKQXW8JNxpD"

# 외부 노출 포트 (NodePort)
mysql_exporter_node_port: 30104

server_aliases:
  "10.0.2.235:9100": "Master Node"
  "10.0.1.90:9100": "Web Node-01"
  "10.0.1.206:9100": "Web Node-02"
  "10.0.2.222:9100": "DB Node"
  "host.docker.internal:9100": "Bastion Host"
