---
#- name: helm 폴더 설치
#  hosts: 
#  roles:
#    - role:
#    - role:

- name: 모니터링 서버 구축 (Docker + Prometheus + Grafana)
  hosts: monitoring_server
  roles:
    - role: docker
    - role: monitoring_stack
    
- name: 타겟 서버들에 Node Exporter 설치
  hosts: target_servers
  become: yes
  roles:
    - node_exporter
