[monitoring_server]
my-bastion ansible_host=localhost ansible_connection=local

[master]
k3s-master ansible_host=10.0.2.235 ansible_user=ubuntu node_role=master

[web]
k3s-web-01 ansible_host=10.0.1.90  ansible_user=ubuntu node_role=web
k3s-web-02 ansible_host=10.0.1.144 ansible_user=ubuntu node_role=web

[db]
k3s-db-01  ansible_host=10.0.2.222 ansible_user=ubuntu node_role=db proxy_url="http://10.0.1.74:3128"

[workers:children]
web
db

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
proxy_server_ip="10.0.1.74"
proxy_port="3128"
proxy_url="http://10.0.1.74:3128"
no_proxy_list="127.0.0.1,localhost,10.0.0.0/16,.svc,.cluster.local"
