[monitoring_server]
#localhost  ansible_connection=local

# 모니터링 당할 서버 ip 추가 
[target_servers]
#node1 ansible_host=192.168.200.133    
#node2 ansible_host=192.168.200.140
[db_server]
#k3-mysql  ansible_host=192.168.200.133

[all:vars]
ansible_user=ubuntu
ansible_connection=ssh


# ---------------------------------------------------------

# 나중에 실제 원격 서버(Ubuntu)에 배포할 경우 (예시)
# [target_servers]
# 192.168.0.100 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/my_key.pem
# -K(대문자)는 sudo 비밀번호, -k(소문자)는 SSH 접속 비밀번호입니다.
