apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx                
  namespace: default      
spec:
  replicas: 2                     
  selector:
    matchLabels:
      app: web-nginx              # deployment가 관리하는 라벨, 이 라벨을 가진 pod만 관리
  template:
    metadata:
      labels:
        app: web-nginx            # deployment가 생성하는 pod에 붙는 라벨
    spec:
      # 생성하는 pod를 web 노드에만 배치
      nodeSelector:
        node-role: web

      containers:
        - name: nginx
          image: nginx:1.27       # Docker Hub의 nginx 공식 이미지
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx-svc 
  namespace: default
spec:
  selector:
    app: web-nginx                # service는 pod 이름 대신 label을 기준으로 트래픽을 전달
  ports:
    - name: http
      port: 80                    # 클러스터 내부에서 접근할 포트
      targetPort: 80              # 실제 컨테이너 포트
      nodePort: 30080            # 외부에서 접속할 포트
  type: NodPort
