---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-mysql
  namespace: default
spec:
  serviceName: "db-mysql-svc"
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql
  template:
    metadata:
      labels:
        app: db-mysql
      #스크랩 허용
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
        prometheus.io/job: "db-mysql"

    spec:
      # DB 노드에만 배치되도록 설정 (해당 노드에 node-role=db 라벨이 있어야 함)
      nodeSelector:
        node-role: db

      # 초기화 컨테이너: HostPath 폴더의 권한을 mysql 유저(999)로 변경
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /var/lib/mysql"]
          volumeMounts:
            - name: mysql-local-storage
              mountPath: /var/lib/mysql

      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--default-authentication-plugin=mysql_native_password"
            - "--performance_schema=ON"
            - "--skip-log-error"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass1234"
            - name: MYSQL_DATABASE
              value: "appdb"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

          volumeMounts:
            - name: mysql-local-storage
              mountPath: /var/lib/mysql

        # mysql exporter 설치
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.15.0
          # 환경 변수가 씹히는 현상을 방지하기 위해 args로 직접 주입
          args:
            - "--mysqld.address=127.0.0.1:3306"
            - "--mysqld.username=root:rootpass1234"
          ports:
            - containerPort: 9104
              name: metrics
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
              
      volumes:
        - name: mysql-local-storage
          hostPath:
            # EC2 인스턴스(Node)의 실제 물리적 경로
            path: /data/mysql-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: db-mysql-svc
  namespace: default
  labels:
    app: db-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
    - port: 9104
      targetPort: 9104
      name: metrics
  clusterIP: None
  selector:
    app: db-mysql
