apiVersion: v1
kind: Node
metadata:
  name: ip-10-0-1-90
  labels:
    node-role: web
---
apiVersion: v1
kind: Node
metadata:
  name: ip-10-0-3-206
  labels:
    node-role: web
---
apiVersion: v1
kind: Node
metadata:
  name: ip-10-0-2-222
  labels:
    node-role: db
---
apiVersion: v1
kind: Node
metadata:
  name: ip-10-0-2-235
  labels:
    node-role: master

