# roles/node_exporter/tasks/main.yml
---
- name: Node Exporter 다운로드 (바이너리)
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: 압축 해제
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: 바이너리 파일을 실행 경로로 이동
  copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes

- name: Node Exporter systemd 서비스 등록
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target

- name: 서비스 시작 및 활성화
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes

    
# 포트는 기본 9100 설정
