---
# 'reload monitoring' 신호를 받았을 때 실행
- name: reload monitoring
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    state: restarted
    remove_orphans: true
