---
# 'reload monitoring' 신호를 받았을 때 실행
- name: reload monitoring
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    state: restarted
    # [추가 권장] 설정이 꼬였을 때를 대비해 의존성 확인 및 정리 옵션
    remove_orphans: true
