# playbooks/cd.yml
---
# [1단계] 매니페스트 파일 복사 및 적용 (Apply)
# 아까 잘 만들어두신 k8s_apply.yml을 가져옵니다.
- import_playbook: k8s_apply.yml

# [2단계] 파드 재시작 및 상태 확인 (Restart & Verify)
- name: CD - Update image & rollout on K3s master
  hosts: master
  become: true
  vars:
    deployment: web-nginx
    container: nginx
    namespace: default
  roles:
    - role: k8s_deploy