---
ansible_user: ubuntu
# [수정됨] 내부망이므로 Proxy 터널링 명령어 삭제, 키 체크만 무시
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# [수정됨] 동적 그룹인 'bastion'의 첫 번째 Private IP를 프록시 주소로 설정
proxy_server_ip: "{{ hostvars[groups['bastion'][0]]['private_ip_address'] }}"
proxy_port: "3128"
proxy_url: "http://{{ proxy_server_ip }}:{{ proxy_port }}"

proxy_env:
  http_proxy: "{{ proxy_url }}"
  https_proxy: "{{ proxy_url }}"
  no_proxy: "127.0.0.1,localhost,10.0.0.0/16,.svc,.cluster.local,{{ ansible_host }}"