# group_vars/monitoring_server.yml
---
target_user: "ubuntu"
monitoring_dir: "/home/{{ target_user }}/monitoring"

# 그라파나(Grafana)
grafana_admin_password: "1234" # 실제 사용할 비번
grafana_port: 3000

# 프로메테우스(Prometheus)
prometheus_retention_time: "2d"
prometheus_retention_size: "300MB"
prometheus_port: 9090

# 자동 다운로드할 대시보드 정보
dashboard_ids:
  - { id: 12708, revision: 1 } # NGINX exporter
  - { id: 1860, revision: 31 } # Node Exporter Full
  - { id: 15282, revision: 1 } # K3S cluster monitoring
  - { id: 7362, revision: 5 } # MySQL Overview
# Discord 또는 Slack에서 만든 Webhook URL
alert_webhook_url: ""

# 외부 노출 포트 (NodePort)
mysql_exporter_node_port: 30104

server_aliases:
  "{{ hostvars[groups['master'][0]]['private_ip_address'] }}:9100": "Master Node"
  "{{ hostvars['K3s-Web-01']['private_ip_address'] }}:9100": "Web Node-01"
  "{{ hostvars['K3s-Web-02']['private_ip_address'] }}:9100": "Web Node-02"
  "{{ hostvars[groups['db'][0]]['private_ip_address'] }}:9100": "DB Node"
  "host.docker.internal:9100": "Bastion Host"
