---
# MySQL Exporter Settings
mysql_user: "exporter"
mysql_password: "exporter"
mysql_host: "{{ hostvars[groups['db'][0]]['private_ip_address'] }}"
mysql_port: 3306
my_ns: "monitoring"
release_name: "mysql-exporter"