{
 "title": "custom dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\n  label_replace(\r\n    label_replace(\r\n      label_replace(\r\n        label_replace(\r\n          kube_node_status_condition{condition=\"Ready\", status=\"true\"},\r\n          \"node\", \"$1\", \"node\", \"ip-(.*)\"\r\n        ),\r\n        \"node\", \"$1.$2\", \"node\", \"([0-9]+)-([0-9]+.*)\"\r\n      ),\r\n      \"node\", \"$1.$2\", \"node\", \"([0-9]+\\\\.[0-9]+)-([0-9]+.*)\"\r\n    ),\r\n    \"node\", \"$1.$2\", \"node\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+)-([0-9]+.*)\"\r\n  )\r\n) by (node)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mysql_up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "노드별 nginx Pod 수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (node) (kube_pod_info{pod=~\"web-nginx.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod 상태 현황",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod별 재시작 횟수 Top 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum by (namespace, pod) (\r\nincrease(kube_pod_container_status_restarts_total[1h])\r\n))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "OOMKilled 컨테이너",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 노드별 CPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (\r\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드별 메모리 사용률",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (avg by (instance) (\r\n    node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes\r\n  ))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드별 Disk 사용률",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance) (\r\n    node_filesystem_avail_bytes{\r\n      mountpoint=\"/\", \r\n      fstype=\"ext4\", \r\n      device=~\"/dev/root\"\r\n    } / \r\n    node_filesystem_size_bytes{\r\n      mountpoint=\"/\", \r\n      fstype=\"ext4\", \r\n      device=~\"/dev/root\"\r\n    }\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "전체 클러스터 재시작 횟수 합계",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pod CPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{\r\n  namespace=\"default\",\r\n  pod=~\"web-nginx.*\"\r\n}[5m])) by (pod) / \r\nsum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"default\",pod=~\"web-nginx.*\"}) by (pod) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "nginx Replica 수",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network 수신",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"ens5|eth.*\"}[5m]) * 8 / 1000000",
     "legendFormat": "{{instance}} 수신"
    }
   ]
  },
  {
   "title": "Network 송신",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\"}[5m]) * 8 / 1000000",
     "legendFormat": "{{instance}} 송신"
    }
   ]
  },
  {
   "title": "mysql 현재 커넥션",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql 실행중인 쿼리",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[5m])\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow Query (Stat)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{container=\"mysql-exporter\"}[5m]) or vector(0)",
     "legendFormat": "db-mysql-0"
    }
   ]
  }
 ]
}